# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vohctTJdktwbuuffp1bNPOWGkLUhZC53
"""

import google.generativeai as genai

genai.configure(api_key="AIzaSyCa5XJ6_qGlV96SLvhEHQq3v5aNxGEzidk")
model = genai.GenerativeModel("gemini-1.5-flash")

chat = model.start_chat(history=[])
chat.send_message("My name is Tommy.")
response = chat.send_message("What is my name?")
print(response.text)