# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qle2FPGz_mgj5NK_yTWuRbUiXHaH7dLW
"""

import google.generativeai as genai

genai.configure(api_key="AIzaSyCa5XJ6_qGlV96SLvhEHQq3v5aNxGEzidk")

model = genai.GenerativeModel("gemini-1.5-flash")
response = model.generate_content("Tell me a fun joke!")

print(response.text)